### ISSUE TITLE
System Tray support

### ISSUE THREAD

**Issue by Sniper435** [javasuns/AsusProfiler#1]
For an improved user experience would it be possible for this to minimise to the system tray?
At present I've noticed that if I open the software, select a profile and close the software this profile is not maintained when I re-open AsusProfiler, minimising to system tray would alleviate this issue and provide a better user experience.

**Comment by javasuns** [comment]
Yes you are right. Profile is lost once you close the app. I’ll fix that on the next release. System tray also.

**Comment by javasuns** [comment]
AsusProfiler v1.1 has just been released. 
https://github.com/javasuns/AsusProfiler/releases/tag/AsusProfileV1.1

**Comment by javasuns** [comment]
Fixed in v1.1

**Comment by lyndonguitar** [comment]
First of all thanks for this amazing too! I've been using it on my Flow X13

one quick question/request, Is it possible to include the option of starting it in windows automatically minimized to tray?

**Comment by javasuns** [comment]
> First of all thanks for this amazing too! I've been using it on my Flow X13
> 
> one quick question/request, Is it possible to include the option of starting it in windows automatically minimized to tray?

Yes, that could do.
Please open a new issue/request and i'll have that on the next release :)
