### ISSUE TITLE
Include a button to enable ArmoryCreate  (StartArmoury.bat)

### ISSUE THREAD

**Issue by serveln** [javasuns/AsusProfiler#3]
It would be nice to have a button that allows to enable Armory Create again in order to have access to enable/disable the eGPU,  change the Screen profiles, etc. By the way excellent contribution, works 👌!

**Comment by javasuns** [comment]
> It would be nice to have a button that allows to enable Armory Create again in order to have access to enable/disable the eGPU, change the Screen profiles, etc. By the way excellent contribution, works 👌!

I'll try to handle this feature within this week. Thank you for your kind words.
